ProjetBlogMVC/Areas/Identity/Controllers/AuthController.cs
using DTO.AuthDTO;
using IServices;
using Microsoft.AspNetCore.Mvc;

namespace ProjetBlogMVC.Areas.Identity.Controllers
{
    public class AuthController(IAuthService authService) : Controller
    {
        [Area("Identity")]
        [HttpGet]
        public IActionResult Register()
        {
            ViewBag.Message = "Register Get";
            return View();
        }

        [Area("Identity")]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterDTO registerDTO)
        {
            try
            {
                await authService.RegisterAsync(registerDTO);
                return RedirectToAction();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

ProjetBlogMVC/Controllers/ArticleController.cs
using DTO.ArticleDTO;
using DTO.ArticlereadDTO;
using DTO.CategoryDTO;
using IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;
using ViewModels.Article;

namespace ProjetBlogMVC.Controllers
{
    public class ArticleController(
        IArticleService articleService,
        ICategoryService categoryService
        ) : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Read(int articleId)
        {
            try
            {string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                return userId == null ?
                    RedirectToAction("Login", "Account", new { area = "Identity" })
                    :
                    View(await articleService.ReadAsync(
                        new ReadArticleDTO(articleId, userId)));
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult<List<GetArticleResponseDTO>>> GetByAuthor()
        {
            try
            {
                string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                    ?? throw new Exception("Utilisateur non connecté.");
                return View(await articleService.GetByAuthorAsync(userId));
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Write()
        {
            List<GetCategoryDTO> categories = await categoryService.GetAllAsync();
            return View(new WriteArticleViewModel(categories));
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Write(WriteArticleRequestDTO requestDTO)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await articleService.WriteAsync(new WriteArticleServiceDTO(requestDTO, userId));
            return RedirectToAction("GetByAuthor");
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult<GetArticleResponseDTO>> Update(int articleId)
        {
            try
            {
                return View(await articleService.GetByIdAsync(articleId));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                ViewBag.InnerMessage = ex.InnerException?.Message;
                return View();
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult<GetArticleResponseDTO>> Update(UpdateArticleRequestDTO updateArticleRequestDTO)
        {
            try
            {
                string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                    ?? throw new Exception("utilisateur non connecté");
                int result = await articleService.UpdateAsync(new UpdateArticleServiceDTO(updateArticleRequestDTO, userId));

                ViewBag.Message = result == -1 ?
                    "Aucune modifications car tous les champs sont identiques à l'original."
                    :
                    "Article Modifié avec succès.";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                ViewBag.InnerMessage = ex.InnerException?.Message;
                return View();
            }
        }

        public async Task<ActionResult> Delete(DeleteArticleRequestDTO requestDTO)
        {
            try
            {
                string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                    ?? throw new Exception("Utilisateur non connecté");
                await articleService.DeleteAsync(new DeleteArticleServiceDTO(requestDTO, userId));
                TempData["Message"] = "Article supprimer avec succès.";
                return RedirectToAction("GetByAuthor");
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["InnerMessage"] = ex.InnerException?.Message;
                return RedirectToAction("GetByAuthor");
            }
        }
    }
}

ProjetBlogMVC/Controllers/ArticleReactionController.cs
using DTO.ArticleReactionDTO;
using IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ProjetBlogMVC.Controllers
{
    public class ArticleReactionController(
        IArticleService articleService,
        IArticleReactionService articleReactionService) : Controller
    {
        
        //[HttpGet]
        //public IActionResult Index(int articleId)
        //{
            
        //    return ViewComponent("ArticleReaction");
        //}

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ToggleLike(int articleId)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                ?? throw new Exception("Utilisateur non identifier.");

            await articleReactionService.ToggleLikeArticleAsync(
                new ToggleArticleReactionDTO(articleId, userId));

            return ViewComponent("ArticleReaction", await articleService.GetByIdAsync(articleId));
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ToggleDislike(int articleId)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                ?? throw new Exception("Utilisateur non identifier.");

            await articleReactionService.ToggleDisLikeArticleAsync(
                new ToggleArticleReactionDTO(articleId, userId));

            return ViewComponent("ArticleReaction", await articleService.GetByIdAsync(articleId));
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ToggleSupport(int articleId)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                ?? throw new Exception("Utilisateur non identifier.");

            await articleReactionService.ToggleSupportArticleAsync(
                new ToggleArticleReactionDTO(articleId, userId));

            return ViewComponent("ArticleReaction", await articleService.GetByIdAsync(articleId));
        }
    }
}

ProjetBlogMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewModels;
using System.Diagnostics;
using IServices;

namespace ProjetBlogMVC.Controllers
{
    public class HomeController(
        ILogger<HomeController> logger,
        IArticleService articleService
        ) : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View(await articleService.GetAllAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetBlogMVC/ViewComponents/ArticleReactionViewComponent.cs
using DTO.ArticleDTO;
using DTO.ArticleReactionDTO;
using IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using Services;
using System.Security.Claims;

namespace ProjetBlogMVC.ViewComponents
{
    public class ArticleReactionViewComponent(IArticleService articleService) : ViewComponent
    {
        [Authorize]
        public IViewComponentResult Invoke(GetArticleResponseDTO article) => View(article);

    }
}

ProjetBlogMVC/Views/Article/GetByAuthor.cshtml
@model List<GetArticleResponseDTO>
@{
    ViewData["Title"] = "Mes Articles";
}
@section styles{
    <link rel="stylesheet" href="~/css/Article/GetByAuthor.css"/>
}

@if(@TempData["Message"] != null)
{
    <div id="liveAlertPlaceholder"></div>
    <script>
        const alertPlaceholder = document.getElementById('liveAlertPlaceholder')
        const appendAlert = (message, type) => {
            const wrapper = document.createElement('div')
            wrapper.innerHTML = [
                `<div class="alert alert-${type} alert-dismissible" role="alert">`,
                `   <div>${message}</div>`,
                '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                '</div>'
            ].join('')

            alertPlaceholder.append(wrapper)
        }
        appendAlert('@TempData["Message"]', 'success')

    </script>
}



<h1>Mes Articles</h1>
<a asp-action="Write">Ecrire un article</a>
<div class="container d-flex flex-wrap justify-content-between">
        @foreach (GetArticleResponseDTO article in @Model)
    {
        <div class="card" style="width: 18rem;">

            <img src="@article.ImageURL" class="card-img-top" alt="...">

            <div class="card-body">
                <h5 class="card-title">@article.Titre</h5>
                <p class="card-text">
                    @article.Description
                </p>
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <span class="fw-bold">Author:</span>
                    @article.AuthorFirstname @article.AuthorLastname
                    <br />
                    <span class="fw-bold">Edité le </span>
                    @article.EditionDate
                    <br />
                    @if(article.UpdatedDate != null)
                    {
                        <span class="fw-bold">Modifié le </span>
                        @article.UpdatedDate
                    }
                        
                </li>

                <li class="list-group-item">
                    <span class="fw-bold">Commentaires: </span>
                    @article.NbComments
                </li>

                <li class="list-group-item">
                    <span class="fw-bold">Lectures: </span>
                    @article.NbReads
                </li>

                <li class="list-group-item">
                    <span class="fw-bold">Likes: </span>
                    @article.NbLikes<br />
                    <span class="fw-bold">DisLikes: </span>
                    @article.NbDisLikes<br />
                    <span class="fw-bold">Supports: </span>
                    @article.NbSupports
                </li>
            </ul>

            <div class="card-body">
                    @*href='@Url.Action("Update", "Article", new{articleId = article.Id})'*@
                <a 

                    asp-controller="Article"
                    asp-action="Update"
                    asp-route-articleId="@article.Id"

                    class="btn btn-outline-primary"
                >
                    Modifier l'article
                </a>
                <a 
                    href='@Url.Action("Delete", "Article", new{articleId = article.Id})' 
                    class="card-link"
                >
                    Supprimmer
                </a>
            </div>
        </div>
    }
</div>


    
<style>

</style>

ProjetBlogMVC/Views/Article/Read.cshtml
@model GetArticleDetailResponseDTO
@{
    ViewData["Title"] = Model.Title;
}
@section styles{
    <link rel="stylesheet" href="~/css/Article/Read.css"/>
}
 @section Scripts{
    <script type="module" src="/js/controllers/ArticleReactionController.js" ></script>
    }
<article>

    <div class="articleDescriptionContainer">
        <img class="articleImage img-fluid" src="@Model.ImageURL" />

        <div>
            <h1>@Model.Title</h1>
            <p onclick="handleToggleLike(@Model.Id)">@Model.Description</p>

            <div id="articleReactionBarContainer">
                @await Component.InvokeAsync("ArticleReaction", new GetArticleResponseDTO(Model))
            </div>
        </div>
    </div>
    

    <p>@Model.Content</p>

</article>

ProjetBlogMVC/Views/Article/Update.cshtml
@model GetArticleResponseDTO
@{
    ViewData["Title"] = "Modifier un article";
}
@section styles{
    <link rel="stylesheet" href="~/css/Article/Update.css"/>
}


<h1>Modifier un article</h1>

@if (@ViewBag.Message != null)
{
    <p>
        @ViewBag.Message
    </p>
    <p>
        @ViewBag.InnerMessage
    </p>
}
else
{
    <form asp-action="Update">
        <input hidden name="articleId" value="@Model.Id" />
        <label>Titre</label><br />
        <input type="text" name="title" value="@Model.Titre" class="w-50 h-25" /><br />

        <label>Description</label>
        <textarea type="text" name="description" class="w-100">@Model.Description</textarea><br />

        <label>Contenu</label>
        <textarea type="text" name="content" class="w-100">@Model.Content</textarea>
        <br />

        <label>Image URL</label><br />
        <input type="text" name="imageURL" value="@Model.ImageURL" class="w-50 h-25" /><br />

        <button>Modifier</button>
        <button>Annuler</button>
    </form>
}

ProjetBlogMVC/Views/Article/Write.cshtml
@model WriteArticleViewModel

<h1>Ecrire un article</h1>

<form asp-action="Write">
    <label>Categorie</label>
    <select name="CategoryId">
        @foreach(GetCategoryDTO category in Model.Categories)
        {
            <option value="@category.Id">@category.Label</option>
        }
    </select>
   
    <label>Titre</label><br />
    <input type="text" name="Title" value="@Model.Title" class="w-50 h-25" /><br />

    <label>Description</label>
    <textarea type="text" name="Description" class="w-100">@Model.Description</textarea><br />

    <label>Contenu</label>
    <textarea type="text" name="Content" class="w-100">@Model.Content</textarea>
    <br />

    <label>Image URL</label><br />
    <input type="text" name="ImageURL" value="@Model.ImageURL" class="w-50 h-25" /><br />

    <button>Modifier</button>
    <button>Annuler</button>
</form>

ProjetBlogMVC/Views/Home/Index.cshtml
@model List<GetArticleResponseDTO>
@{
    ViewData["Title"] = "Home Page";
}
@section styles{
    <link rel="stylesheet" href="~/css/Home/Index.css"/>
}
<h1>Bienvenue</h1>


<div class="container d-flex flex-wrap justify-content-evenly">
   
    @foreach (GetArticleResponseDTO article in @Model)
    {
        <div class="card mb-5 shadow mx-auto" style="width:325px">

            <img src="@article.ImageURL" class="card-img-top" alt="">

            @await Component.InvokeAsync("ArticleReaction" , article)

            <div class="card-body d-flex flex-column justify-content-between">
                <div>
                    <h5 class="card-title">@article.Titre</h5>
                    <p class="card-text fs-6">@article.Description</p>
                </div>
                <a asp-action="Read" asp-controller="Article" asp-route-articleId="@article.Id" class="btn btn-primary">Lire l'article</a>
            </div>



            
        </div>

    }
</div>

ProjetBlogMVC/Views/Shared/Components/ArticleReaction/Default.cshtml
@model GetArticleResponseDTO

<link rel="stylesheet" href="~/css/ViewComponents/ArticleReaction.css" />



<div id="articleReactionContainer" class="articleReactionContainer d-flex justify-content-between shadow">
    <div class="likeContainer" id="likeContainer" data-article-id="@Model.Id">
        <img src="~/assets/icons/like.svg" height="20px" width="20px" alt="Une main avec le pouce pointé vers le haut." />
        <p>@Model.NbLikes</p>
    </div>

    <div class="disLikeContainer" id="dislikeContainer" data-article-id="@Model.Id">
        <img src="~/assets/icons/like.svg" height="20px" width="20px" alt="Une main avec le pouce pointé vers le bas." />
        <p>@Model.NbDisLikes</p>
    </div>

    <div class="supportContainer" id="supportContainer" data-article-id="@Model.Id">
        <img src="~/assets/icons/support.svg" height="25px" width="25px" alt="Une main qui soutien quelque chose." />
        <p>@Model.NbSupports</p>
    </div>
</div>

ProjetBlogMVC/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetBlogMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetBlogMVC.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("styles", false)
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a 
                    class="navbar-brand" 
                    asp-area="" 
                    asp-controller="Home" 
                    asp-action="Index"
                >
                    Articles
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a 
                                    class="nav-link text-dark" 
                                    asp-area="" 
                                    asp-controller="Article" 
                                    asp-action="GetByAuthor"
                                >
                                    Mes articles
                                </a>
                            </li>
                        
                            <li class="nav-item">
                                <a 
                                    class="nav-link text-dark" 
                                    asp-area="" 
                                    asp-controller="Article" 
                                    asp-action="Read"
                                >
                                    Commentaires
                                </a>
                            </li>

                            <li class="nav-item">
                                <a 
                                    class="nav-link text-dark" 
                                    asp-area="" 
                                    asp-controller="Article" 
                                    asp-action="Read"
                                >
                                    Stats
                                </a>
                            </li>
                        }

                        <li class="nav-item">
                            <a 
                                class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="Home" 
                                asp-action="Privacy"
                            >
                                Privacy
                            </a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>

    <div class="container customStyle">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjetBlogMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>